image: docker:git
services: docker:dind

stages:
  - build

variables:
  IMAGE: gitlab.polyswarm.io:3343/polyswarm/documentation

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - ls -lah
