stages:
  - build
  - deploy

build:
  stage: build
  image: $CI_REGISTRY_IMAGE
  script:
    - cd app
    - source ~/.bashrc
    - if [ ! -e node_modules ]; then npm install --silent; fi
    - bundle install --path vendor/bundle
    - npx gulp --all-langs --production
    - bundle exec htmlproofer ./dist --check-html --url-ignore '/#.*/' --disable-external
  cache:
    key: v001
    paths:
      - app/node_modules/
      - app/vendor/
  artifacts:
    paths:
      - app/dist

deploy:
  stage: deploy
  image: $CI_REGISTRY_IMAGE
  only:
    - master
  script:
    - cd app/dist
    - git config --global user.email "info@polyswarm.io"
    - git config --global user.name "PolySwarm"
    - git init
    - git add . && git commit -am "Deployed with GitLab :rocket:"
    - git remote add origin https://${GITHUB_USER_ID}:${GITHUB_TOKEN}@github.com/polyswarm/polyswarm.github.io.git
    - git push --mirror origin
