stages:
  - build
  - test

variables:
  DOCKER_FULL_PATH: gitlab.polyswarm.io:3343/polyswarm/documentation

build:
  stage: build
  image: $DOCKER_FULL_PATH
  script:
    - cd app
    - source ~/.bashrc
    - npm install --silent
    - bundle check || bundle install --path vendor/bundle
    - npx gulp --all-langs --production
  artifacts:
    paths:
      - app/dist
      - app/node_modules
      - app/vendor/bundle

test:
  stage: test
  image: $DOCKER_FULL_PATH
  script:
    - cd app
    - bundle exec htmlproofer ./dist --check-html --url-ignore '/#.*/' --disable-external
