stages:
  - build
  - deploy

variables:
  DOCKER_FULL_PATH: gitlab.polyswarm.io:3343/polyswarm/documentation

build:
  stage: build
  image: $DOCKER_FULL_PATH
  script:
    - cd app
    - source ~/.bashrc
    - if [ ! -e node_modules ]; then npm install --silent; fi
    - if [ ! -e vendor ]; then bundle install --path vendor/bundle; fi
    - npx gulp --all-langs --production
    - bundle exec htmlproofer ./dist --check-html --url-ignore '/#.*/' --disable-external
  cache:
    key: v001
    paths:
      - app/node_modules/
      - app/vendor/
  artifacts:
    paths:
      - app/dist

deploy:
  stage: deploy
  image: $DOCKER_FULL_PATH
  # only:
  #   - master
  script:
    - cd app/dist
    - git init
    - git add . && git commit -am "Deployed with GitLab"
    - git remote add origin https://${GITHUB_USER_ID}:${GITHUB_TOKEN}@github.com/polyswarm/polyswarm.github.io.git
    - git push origin master
