stages:
  - build

compile:
  stage: build
  image: mrjoshc/jekyll-node:2.5.1-8.11.3
  script:
    - cd app
    - source ~/.bashrc
    - npm install --silent
    - bundle check || bundle install --path vendor/bundle
    - npx gulp --all-langs --production
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - app/node_modules/
      - app/vendor/bundle/
