# Site data
url: http://example.com
baseurl: ""
company: PolySwarm Pte. Ltd.
privacyurl: /privacy-terms/
whitepaperpdf: /polyswarm-whitepaper.pdf
langs:
 - name: DE
   fullname: Deutsch
   url: "/de/"
 - name: EN
   fullname: English
   url: "/"
 - name: ES
   fullname: Español
   url: "/es/"
 - name: FR
   fullname: Français
   url: "/fr/"
 - name: RU
   fullname: Русский
   url: "/ru/"
 - name: KR
   fullname: 한국어
   url: "/kr/"
 - name: JA
   fullname: 日本語
   url: "/ja/"
 - name: ZH
   fullname: 中文
   url: "/zh/"

# Build settings
destination: tmp
layouts_dir: src/theme/_layouts
includes_dir: src/theme/_includes
exclude:
  - dist
  - gulp
  - node_modules
  - src
  - tmp
  - vendor
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "l-docs"

# Markdown settings
markdown: kramdown

# Plugins
plugins:
  # Multiple languages plugin will be local until #122 is merged
  # https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/pull/122
  # - jekyll-multiple-languages-plugin

# i18n
languages:
  - en
  - fr
