# Site data
url: https://docs.polyswarm.io
rooturl: https://polyswarm.io
baseurl: ""
gtm_id: GTM-KVL483J

# Social media
social_media:
  facebook: https://www.facebook.com/PolySwarm
  twitter: https://twitter.com/polyswarm
  linkedin: https://www.linkedin.com/company/polyswarm
  youtube: https://www.youtube.com/channel/UClkA8JVQ--oMsPomOKM85fA
  github: https://github.com/polyswarm
  medium: https://medium.com/polyswarm

# Languages
langs:
 - name: DE
   fullname: Deutsch
   url: /de/
 - name: EN
   fullname: English
   url: /
 - name: ES
   fullname: Español
   url: /es/
 - name: FR
   fullname: Français
   url: /fr/
 - name: RU
   fullname: Русский
   url: /ru/
 - name: KR
   fullname: 한국어
   url: /kr/
 - name: JA
   fullname: 日本語
   url: /ja/
 - name: ZH
   fullname: 中文
   url: /zh/

# Build settings
destination: tmp
layouts_dir: src/theme/_layouts
includes_dir: src/theme/_includes
exclude:
  - dist
  - gulp
  - node_modules
  - src
  - tmp
  - vendor
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: l-docs

# Markdown settings
markdown: kramdown

# Plugins
plugins:
  # Multiple languages plugin will be local until #122 is merged
  # https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/pull/122
  # - jekyll-multiple-languages-plugin
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Multiple Languages Plugin Settings
languages:
  - en
  - zh
  - ja
  - es
  - fr
  - de
  - ru
  - kr

# Jekyll Seo Tag Plugin Settings
logo: /assets/images/favicon/siteicon.png
title: PolySwarm
author:
  name: PolySwarm Pte. Ltd.
  email: info@polyswarm.io
  twitter: polyswarm
social:
  name: PolySwarm
  links:
    - https://www.facebook.com/PolySwarm
    - https://twitter.com/polyswarm
    - https://www.linkedin.com/company/polyswarm
    - https://www.youtube.com/channel/UClkA8JVQ--oMsPomOKM85fA
    - https://github.com/polyswarm
    - https://medium.com/polyswarm
